//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DG.Tweening;

namespace QFramework.MFO
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class LevelManagePanelData : QFramework.UIPanelData
    {
        public LevelDataList mLevelData = new LevelDataList();

        public LevelManagePanelData()
        {
            mLevelData.InitLoadJson();
        }
    }
    
    public partial class LevelManagePanel : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as LevelManagePanelData ?? new LevelManagePanelData();
            // please add init code here

            Content.InitLevelItem(LevelItem,mData.mLevelData);

            ViewToggle.onValueChanged.AddListener(on =>
            {
                if (on)
                {
                    ToggleText.text = ">";
                    PlayerItemView.rectTransform.DOLocalMoveX(692f, 0.5f);
                }
                else
                {
                    ToggleText.text = "<";
                    PlayerItemView.rectTransform.DOLocalMoveX(1024f, 0.5f);
                }
            });
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
