//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.MFO
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class LevelManagePanel
    {
        
        public const string NAME = "LevelManagePanel";
        
        [SerializeField()]
        public UnityEngine.UI.Image LevelItemView;
        
        [SerializeField()]
        public LevelListView Content;
        
        [SerializeField()]
        public UnityEngine.UI.Toggle ViewToggle;
        
        [SerializeField()]
        public UnityEngine.UI.Text ToggleText;
        
        [SerializeField()]
        public LevelItem LevelItem;
        
        private LevelManagePanelData mPrivateData = null;
        
        public LevelManagePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new LevelManagePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            LevelItemView = null;
            Content = null;
            ViewToggle = null;
            ToggleText = null;
            LevelItem = null;
            mData = null;
        }
    }
}
