//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.MFO
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class PlayerManagePanel
    {
        
        public const string NAME = "PlayerManagePanel";
        
        [SerializeField()]
        public PlayItem PlayerItem;
        
        [SerializeField()]
        public UnityEngine.UI.Image PlayerItemView;
        
        [SerializeField()]
        public PlayerListView Content;
        
        [SerializeField()]
        public UnityEngine.UI.Toggle ViewToggle;
        
        [SerializeField()]
        public UnityEngine.UI.Text ToggleText;
        
        private PlayerManagePanelData mPrivateData = null;
        
        public PlayerManagePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new PlayerManagePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            PlayerItem = null;
            PlayerItemView = null;
            Content = null;
            ViewToggle = null;
            ToggleText = null;
            mData = null;
        }
    }
}
