//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DG.Tweening;

namespace QFramework.MFO
{
    using UniRx;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class PlayerManagePanelData : QFramework.UIPanelData
    {
        public PlayerDataList mModel = new PlayerDataList();

        public PlayerManagePanelData()
        {
            mModel.InitLoadJson();
        }
    }
    
    public partial class PlayerManagePanel : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        /// <summary>
        /// 初始化数据
        /// </summary>
        /// <param name="uiData"></param>
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as PlayerManagePanelData ?? new PlayerManagePanelData();
            // please add init code here

            Content.InitPlayerItem(PlayerItem,mData.mModel);

            ViewToggle.onValueChanged.AddListener(on =>
            {
                if (on)
                {
                    ToggleText.text = "<";
                    PlayerItemView.rectTransform.DOLocalMoveX(0f,1f);
                }
                else
                {
                    ToggleText.text = ">";
                    PlayerItemView.rectTransform.DOLocalMoveX(-365f, 1f);
                }
            });
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
