// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Mario_prefab
    {
        public const string BundleName = "mario_prefab";
        public const string MARIO = "mario";
    }
}
