//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Characters_prefab
    {
        public const string BundleName = "characters_prefab";
        public const string CHARACTERS = "characters";
    }
    public class Gamescene_1_json
    {
        public const string BundleName = "gamescene_1_json";
        public const string GAMESCENE_1 = "gamescene_1";
    }
    public class Gamescene_1_prefab
    {
        public const string BundleName = "gamescene_1_prefab";
        public const string GAMESCENE_1 = "gamescene_1";
    }
    public class Ground_1_prefab
    {
        public const string BundleName = "ground_1_prefab";
        public const string GROUND_1 = "ground_1";
    }
    public class Ground_2_prefab
    {
        public const string BundleName = "ground_2_prefab";
        public const string GROUND_2 = "ground_2";
    }
    public class Ground_end_prefab
    {
        public const string BundleName = "ground_end_prefab";
        public const string GROUND_END = "ground_end";
    }
    public class Ground_start_prefab
    {
        public const string BundleName = "ground_start_prefab";
        public const string GROUND_START = "ground_start";
    }
    public class Mainscene_prefab
    {
        public const string BundleName = "mainscene_prefab";
        public const string MAINSCENE = "mainscene";
    }
    public class Mario_prefab
    {
        public const string BundleName = "mario_prefab";
        public const string MARIO = "mario";
    }
    public class Pickcoinpool_prefab
    {
        public const string BundleName = "pickcoinpool_prefab";
        public const string PICKCOINPOOL = "pickcoinpool";
    }
    public class Pickcoinprefab_prefab
    {
        public const string BundleName = "pickcoinprefab_prefab";
        public const string PICKCOINPREFAB = "pickcoinprefab";
    }
    public class Player_2_prefab
    {
        public const string BundleName = "player_2_prefab";
        public const string PLAYER_2 = "player_2";
    }
    public class Player_3_prefab
    {
        public const string BundleName = "player_3_prefab";
        public const string PLAYER_3 = "player_3";
    }
    public class Player_4_prefab
    {
        public const string BundleName = "player_4_prefab";
        public const string PLAYER_4 = "player_4";
    }
    public class Player_5_prefab
    {
        public const string BundleName = "player_5_prefab";
        public const string PLAYER_5 = "player_5";
    }
    public class Playeritem_json
    {
        public const string BundleName = "playeritem_json";
        public const string PLAYERITEM = "playeritem";
    }
    public class Playermanagepanel_prefab
    {
        public const string BundleName = "playermanagepanel_prefab";
        public const string PLAYERMANAGEPANEL = "playermanagepanel";
    }
    public class Selectlevel_prefab
    {
        public const string BundleName = "selectlevel_prefab";
        public const string SELECTLEVEL = "selectlevel";
    }
    public class Selectplayer_prefab
    {
        public const string BundleName = "selectplayer_prefab";
        public const string SELECTPLAYER = "selectplayer";
    }
}
